### ISSUE TITLE
No work in antd-init

### ISSUE THREAD

**Issue by afc163** [dora-js/dora-plugin-livereload#2]
https://github.com/ant-design/antd-init/blob/master/boilerplate/package.json#L32

**Comment by afc163** [comment]
Ant seem not support for less files

**Comment by afc163** [comment]
目前要手动加 `.html` 后缀才行。

**Comment by sorrycc** [comment]
配合 [LiveReload Chrome Plugin](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) 用吧。

**Comment by soda-x** [comment]
koa 中间件 koa-static 有个 index 的逻辑，在不指定的情况下默认会去根目录下找 index.html

所以该插件只需增强下 `pathname` 为 `/` 的逻辑即可
