### ISSUE TITLE
Use localhost over localIP

### ISSUE THREAD

**Issue by afc163** [dora-js/dora-plugin-livereload#3]
https://github.com/dora-js/dora-plugin-livereload/blob/c13503f8868124b5f03c363384e0c83cfe064a78/src/index.js#L141

**Comment by soda-x** [comment]
Considering mobile client, I think local ip address  is the best choice.

**Comment by afc163** [comment]
有时候在 vpn 环境下获取的 ip 是错误的... 导致一直在 pending

**Comment by sorrycc** [comment]
通过参数配置支持不同场景吧，dora-plugin-proxy 也遇到 local ip 的问题，后来换成 localhost 了。

**Comment by soda-x** [comment]
~~我在插件内实现下根据网络情况自动切换  ip 或 localhost 吧. ~~
~~参数还是不开放出来了.~~

**Comment by soda-x** [comment]
在原来的基础上新增了一个参数来解决

参数为 `injectHost` 默认为 ip 地址，可以根据自己需要设置成 `localhost`
