### ISSUE TITLE
injectHost 可以配置相对路径

### ISSUE THREAD

**Issue by afc163** [dora-js/dora-plugin-livereload#6]
希望可以路径配置成 `<script src='./livereload.js'></script>`

这样方便分享本地服务地址给其他人看。

**Comment by sorrycc** [comment]
分享给别人看还需要 livereload 吗?

**Comment by afc163** [comment]
本地起了一个调试服务，给别人看效果时，通常给别人的页面地址是 `http://{本机ip}:端口/`。

此时如果 livereload 地址写死是 `127.0.0.1`，对方就看不了了。

**Comment by soda-x** [comment]
嗯 这就是当时默认用 ip 的原因，分享给别人看是一种场景，还有一种场景是在手机上调试。
配置成相对路径似乎不行因为 livereload 默认有自己的端口号这个和本地起 server 的端口号是不一致的。

想想有没有其他的方式，之前想到了用 Bonjour 在一个网域内可以随意分享也不会被 ip 换了而要重启 server 而烦恼。 但缺点就是要在同一网域内。

**Comment by afc163** [comment]
对，不能是 `<script src='./livereload.js'></script>`，我搞错了。
