### ISSUE TITLE
ip 不对

### ISSUE THREAD

**Issue by yiminghe** [dora-js/dora-plugin-livereload#7]
10.x:8001/  html 内产生代码

```
<script src='http://192.x:35729/livereload.js'></script>
```

不能用 192 的 ip

**Comment by yiminghe** [comment]
@sorrycc

**Comment by soda-x** [comment]
你可以选择注入一个自己想要的 host

**Comment by soda-x** [comment]
配置项是 injectHost

**Comment by soda-x** [comment]
试了下默认拿到的是 10.x

你要不自己使用 ifconfig 看看自己的网络情况

另外使用 document write 的方式不妥吧，有些业务里面是绑定 host 的

**Comment by yiminghe** [comment]
之前是开了虚拟机，现在不开虚拟机好了，默认用 document.write 好了

**Comment by soda-x** [comment]
那下个版本加上吧
