### ISSUE TITLE
IE 下报 html 格式错误

### ISSUE THREAD

**Issue by afc163** [dora-js/dora-plugin-livereload#8]
![](https://zos.alipayobjects.com/rmsportal/JTHsySQKHNppHfC.png)

script 标签直接插入到 doctype 后面会破坏标准 html 格式。

https://github.com/dora-js/dora-plugin-livereload/blob/632f72030492f3697999876e2752d21f795a6323/src/index.js#L149

**Comment by soda-x** [comment]
所有的 IE 都会报这个错么?

**Comment by afc163** [comment]
IE 9/10/11 都会。

**Comment by afc163** [comment]
而且放在顶部容易阻止渲染，放在底部如何？

**Comment by soda-x** [comment]
好 那我明天处理下
